### ISSUE TITLE
Icons - Broken link

### ISSUE THREAD

**Issue by JuanPabloDiaz** [cosmoart/Freesets#16]
1. License's URL for **_iconify design_** is not working.

    ### problem
    
    https://iconify.design/license/
    
    ### Solution
    
    https://iconify.design/#license

2. License's URL for **_Manypixels_** is not correct, a better URL could be `https://www.manypixels.co/terms-of-service`
3. **_Iconsvg_** is missing the `MIT` license, which can be found in the footer.
4. License's URL for **Core UI** is not working.

    ### problem

    https://coreui.io/license/
    
    ### Solution

    https://github.com/coreui/coreui/blob/v5/LICENSE
    - **MIT** license instead of Freemium
5. **_Potlab icons_** site down

![url](https://github.com/cosmoart/Freesets/assets/25883220/ee74fbe6-f3dc-437b-aaa4-0afbb57c4afb)

**Comment by cosmoart** [comment]
Thank you. Solved.
