### ISSUE TITLE
Add a search bar

### ISSUE THREAD

**Issue by Bashamega** [cosmoart/Freesets#18]
Hello:)
My idea is to add a search bar when the user selects a category to make it easier for the user search the list.
I would like to work on it

**Comment by cosmoart** [comment]
I plan to do it, but if you want to do it go ahead.

**Comment by Bashamega** [comment]
> I plan to do it, but if you want to do it go ahead.

Please assign me

**Comment by cosmoart** [comment]
Don't worry, if you want, you can also contribute with new resources just by editing the JSONs following the [contribution guide](https://github.com/cosmoart/Freesets/blob/main/CONTRIBUTING.md).
