### ISSUE TITLE
Tool suggestion: Freeter

### ISSUE THREAD

**Issue by alexk111** [cosmoart/Freesets#32]
Hi there! I'd like to suggest a new item for the tools section.
Homepage: https://freeter.io/
GH Repo: https://github.com/FreeterApp/Freeter
Post on what it does: https://dev.to/alexk/how-i-boosted-my-productivity-while-working-on-multiple-projects-3h71/
Free & Open-Source under the GPLv3 license.

**Comment by cosmoart** [comment]
Added

**Comment by alexk111** [comment]
Thanks 👍
