### ISSUE TITLE
Add Resources : React Skeleton & Mockups tool

### ISSUE THREAD

**Issue by vcntttt** [cosmoart/Freesets#4]
Hi! I would like to add 2 new ones in the tools section.
https://skeletonreact.com/
https://shots.so/

**Comment by cosmoart** [comment]
Hi, right now you can't add the resources directly because I moved the images and database from the repository, so I added them manually: you can now find them in the [tools section](https://freesets.vercel.app/tools).

Thanks for the suggestions!
