### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by JuanPabloDiaz** [cosmoart/Freesets#8]
### Discussed in https://github.com/cosmoart/Freesets/discussions/5

<div type='discussions-op-text'>

<sup>Originally posted by **JuanPabloDiaz** February  8, 2024</sup>
I forked the project and was planning on doing a PR with the new resources I have. But I run into an issue which I believe it's because I don't have the env variables. (**Error: supabaseUrl is required**.)

If you could guide me on how to fix that, I will be happy to make some changes and do the PR.</div>

Otherwise, I created a list of some resources that I would like to share.

**Comment by cosmoart** [comment]
Thanks for taking the time, you can send that list in this Issue.

**Comment by JuanPabloDiaz** [comment]
Please let me know how I can contribute to the code; I would like to learn and understand what I was probable doing wrong. 


### Here is the list of resources that I would like to add into this cool project:

## Icons

- [react icons](https://react-icons.github.io/react-icons/)
- [icon icons](https://icon-icons.com/)
- [flat icon](https://www.flaticon.com/)
- [font awesome](https://fontawesome.com/)
- [material-ui](https://material-ui.com/)
- [tabler icons](https://tablericons.com/)
- [twemoji](https://twemoji.twitter.com/)
- [icon scout](https://iconscout.com/unicons)
- [zondicons](http://www.zondicons.com/)
- [boxicons](https://boxicons.com/)
- [feather icons](https://feathericons.com/)
- [octicons](https://primer.style/octicons/)
- [radix](https://www.radix-ui.com/icons)
- [favicon](https://favicon.io/)
- [realfavicongenerator](https://realfavicongenerator.net/)

## Photos

- [picjumbo](https://picjumbo.com/)

## Colors

- [colorwave](https://colorwave.dev/)

## Blogs

- [medium](https://medium.com/)
- [chat.zulip](https://chat.zulip.org/)
- [hashnode](https://hashnode.com/)
- [a list apart](https://alistapart.com/)
- [site point](https://www.sitepoint.com/)
- [codrops](https://tympanus.net/codrops/)
- [speckyboy](https://speckyboy.com/)

## Tools

- [gitHub profile badges](https://home.aveek.io/GitHub-Profile-Badges/)
- [compress jpeg](https://compressjpeg.com/)
- [free convert](https://www.freeconvert.com/)
- [compress jpg](https://compressjpg.net/)
- [picresize](https://picresize.com/)
- [tinypng](https://tinypng.com/)
- [imagecompressor](https://www.imagecompressor.com/)
- [pdftoimage](https://pdftoimage.com/)
- [cssgridgarden](https://cssgridgarden.com/)
- [flexboxfroggy](https://flexboxfroggy.com/)
- [flukeout](https://flukeout.github.io/)
- [codingfantasy](https://codingfantasy.com/)
- [Material Design](https://m3.material.io/)
- [Figma](https://www.figma.com/)
- [Sketch](https://www.sketch.com/)
- [Canva](https://www.canva.com/)

## Components

- [mamba-ui](https://mamba-ui.com/)
- [merakiui](https://merakiui.com/)
- [chakra-ui](https://chakra-ui.com/)
- [tailwind components](https://tailwindcomponents.com/)
- [tuk](https://tuk.dev/)
- [tailwind toolbox](https://www.tailwindtoolbox.com/)
- [tailwind ui](https://tailwindui.com/)

**Comment by cosmoart** [comment]
Now you can make the contribution directly in the code, to do this I recommend you reading the [contribution guide](https://github.com/cosmoart/freesets/blob/main/CONTRIBUTING.md) first.

But first remember that the resources should not be repeated and some of your list are already included in Freesets.
